version: "3"

services:
  website:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
      - /usr/src/.next
    command: npm run dev